In [29]:
import pandas as pd
df_matches = pd.read_csv("data/matches.csv")

In [30]:
df_matches

,edition,round,score,team1,team2,url,venue,year
0,1930-URUGUAY,GROUP_STAGE,4-1 (3-0),France,Mexico (México),1930_URUGUAY_FS.htm#1-WC-30-I,Montevideo.,1930
1,1930-URUGUAY,GROUP_STAGE,3-0 (2-0),USA,Belgium (België),1930_URUGUAY_FS.htm#13-WC-30-I,Montevideo.,1930
2,1930-URUGUAY,GROUP_STAGE,2-1 (2-0),Yugoslavia (Југославија),Brazil (Brasil),1930_URUGUAY_FS.htm#7-WC-30-I,Montevideo.,1930
3,1930-URUGUAY,GROUP_STAGE,3-1 (1-0),Romania (România),Peru (Perú),1930_URUGUAY_FS.htm#10-WC-30-I,Montevideo.,1930
4,1930-URUGUAY,GROUP_STAGE,1-0 (0-0),Argentina,France,1930_URUGUAY_FS.htm#2-WC-30-I,Montevideo.,1930
...,...,...,...,...,...,...,...,...
7294,2014-BRAZIL,1/4_FINAL,(C),3,4,2014_BRAZIL_FS.htm#832-WC-14-III,Salvador.,2014
7295,2014-BRAZIL,1/2_FINAL,(X),A,B,2014_BRAZIL_FS.htm#833-WC-14-IV,Belo Horizonte.,2014
7296,2014-BRAZIL,1/2_FINAL,(Y),C,D,2014_BRAZIL_FS.htm#834-WC-14-IV,São_Paulo.,2014
7297,2014-BRAZIL,PLACES_3&4,xxx,LOSER X,LOSER Y,2014_BRAZIL_FS.htm#835-WC-14-V,Brasília.,2014
7298,2014-BRAZIL,_FINAL,xxx,WINNER X,WINNER Y,2014_BRAZIL_FS.htm#836-WC-14-VI,Rio de Janeiro.,2014

In [31]:
df_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7299 entries, 0 to 7298
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   edition  7299 non-null   object
 1   round    7299 non-null   object
 2   score    7299 non-null   object
 3   team1    7299 non-null   object
 4   team2    7299 non-null   object
 5   url      7299 non-null   object
 6   venue    7299 non-null   object
 7   year     7299 non-null   int64
dtypes: int64(1), object(7)
memory usage: 456.3+ KB

In [32]:
df_matches["round"].value_counts()

round
PRELIMINARY-Europe         2332
PRELIMINARY-Africa         1132
PRELIMINARY-Asia            976
PRELIMINARY-N/C.America     965
PRELIMINARY-S.America       631
GROUP_STAGE                 580
PRELIMINARY-As./O.          173
PRELIMINARY-Oceania         171
1/8_FINAL                    64
1/4_FINAL                    62
1/2_FINAL                    34
SEMIFINAL_STAGE              24
PRELIMINARY-O./As.           22
_FINAL                       19
PLACES_3&4                   18
FIRST                        17
PRELIMINARY-Euro/As.         16
PRELIMINARY-Eur./N.E.        15
PRELIMINARY-Eu./Afr.         13
QUARTERFINAL_STAGE           12
PRELIMINARY-Afr./As.          7
PRELIMINARY-E./Afr./As.       6
FINAL_ROUND                   6
PRELIMINARY-N.E.              2
PRELIMINARY-Af./As./O.        2
Name: count, dtype: int64

In [33]:
# Suppression des matchs qui ne nous interessent pas 
clean_round = df_matches[df_matches["round"].str.contains("PRELIMINARY", na = False)].index
df_matches = df_matches.drop(clean_round)

In [34]:
df_matches["round"].value_counts()

round
GROUP_STAGE           580
1/8_FINAL              64
1/4_FINAL              62
1/2_FINAL              34
SEMIFINAL_STAGE        24
_FINAL                 19
PLACES_3&4             18
FIRST                  17
QUARTERFINAL_STAGE     12
FINAL_ROUND             6
Name: count, dtype: int64

In [35]:
# Renomme les matchs avec les bonnes nominations 
df_matches["round"] = df_matches["round"].replace(to_replace={"GROUP_STAGE":"Poules", "1/8_FINAL": "Huitièmes de finale","FIRST": "Huitièmes de finale", "1/4_FINAL" : "Quarts de finale", "QUARTERFINAL_STAGE": "Quarts de finale", "1/2_FINAL" : "Demi-finales", "SEMIFINAL_STAGE": "Demi-finales", "_FINAL" : "Finale", "FINAL_ROUND":"Finale", "PLACES_3&4" : "Troisième place"  })

In [36]:
# match apres 2010 
df_matches[df_matches["year"] > 2010].head(10)["year"].value_counts()

year
2014    10
Name: count, dtype: int64

In [37]:
# Pas de scores pour 2014
df_matches[df_matches["year"] > 2010].head(10)

,edition,round,score,team1,team2,url,venue,year
7235,2014-BRAZIL,Poules,xxx,Brazil (Brasil),Croatia (Hrvatska),2014_BRAZIL_FS.htm#773-WC-14-I,São_Paulo.,2014
7236,2014-BRAZIL,Poules,xxx,Mexico (México),Cameroon (Cameroun),2014_BRAZIL_FS.htm#774-WC-14-I,Natal.,2014
7237,2014-BRAZIL,Poules,xxx,Spain (España),Netherlands (Nederland),2014_BRAZIL_FS.htm#775-WC-14-I,Salvador.,2014
7238,2014-BRAZIL,Poules,xxx,Chile,Australia,2014_BRAZIL_FS.htm#776-WC-14-I,Cuiabá.,2014
7239,2014-BRAZIL,Poules,xxx,Colombia,Greece (Ελλάδα),2014_BRAZIL_FS.htm#777-WC-14-I,Belo Horizonte.,2014
7240,2014-BRAZIL,Poules,xxx,Uruguay,Costa Rica,2014_BRAZIL_FS.htm#778-WC-14-I,Fortaleza.,2014
7241,2014-BRAZIL,Poules,xxx,England,Italy (Italia),2014_BRAZIL_FS.htm#779-WC-14-I,Manaus.,2014
7242,2014-BRAZIL,Poules,xxx,Ivory Coast (Côte d’Ivoire),Japan (日本),2014_BRAZIL_FS.htm#780-WC-14-I,Recife.,2014
7243,2014-BRAZIL,Poules,xxx,Switzerland (Schweiz / Suisse),Ecuador,2014_BRAZIL_FS.htm#781-WC-14-I,Brasília.,2014
7244,2014-BRAZIL,Poules,xxx,France,Honduras,2014_BRAZIL_FS.htm#782-WC-14-I,Porto_Alegre.,2014

In [38]:
# donc on drop ces lignes :
df_matches = df_matches.drop(df_matches[df_matches["year"] > 2010].index)

In [39]:
df_matches.head(1)

,edition,round,score,team1,team2,url,venue,year
0,1930-URUGUAY,Poules,4-1 (3-0),France,Mexico (México),1930_URUGUAY_FS.htm#1-WC-30-I,Montevideo.,1930

In [40]:
#Colonne Score : 1er valeur -> score de fin de match, 2e valeur -> score à la mi temps. on veut garder seulement le score final 
df_matches["score final"] = df_matches["score"].str.split(" ").str[0] 
df_matches.head(1)

,edition,round,score,team1,team2,url,venue,year,score final
0,1930-URUGUAY,Poules,4-1 (3-0),France,Mexico (México),1930_URUGUAY_FS.htm#1-WC-30-I,Montevideo.,1930,4-1

In [41]:
# Attribuer le nombre de buts a chaque équipes : 
df_matches["home_result"] = df_matches["score final"].str.split("-").str[0]
df_matches["away_result"] = df_matches["score final"].str.split("-").str[1]
df_matches.head(1)

,edition,round,score,team1,team2,url,venue,year,score final,home_result,away_result
0,1930-URUGUAY,Poules,4-1 (3-0),France,Mexico (México),1930_URUGUAY_FS.htm#1-WC-30-I,Montevideo.,1930,4-1,4,1

In [42]:
#Suppression colonnes dont on a plus besoin 
df_matches = df_matches.drop(columns=["url", "score", "score final"])

In [43]:
# Renomme les colonnes
df_matches = df_matches.rename(columns = {"team1" : "home_team", "team2": "away_team", "year":"date"})

In [44]:
# Creation colonne resultats : 
def function(row): 
    if row["home_result"]> row["away_result"]:
        return "home_team"
    elif  row["home_result"]< row["away_result"] :
        return "away_home"
    else : 
        return "draw"

df_matches["result"] = df_matches.apply(function, axis=1)

In [45]:
df_matches.head(3)

,edition,round,home_team,away_team,venue,date,home_result,away_result,result
0,1930-URUGUAY,Poules,France,Mexico (México),Montevideo.,1930,4,1,home_team
1,1930-URUGUAY,Poules,USA,Belgium (België),Montevideo.,1930,3,0,home_team
2,1930-URUGUAY,Poules,Yugoslavia (Југославија),Brazil (Brasil),Montevideo.,1930,2,1,home_team

In [46]:
# On recupere la ville depuis la colonne venue et on enlève le point en fin de mot
df_matches["city"] = df_matches["venue"].str.replace('.','')

In [47]:
# On recupere la date depuis la colonne edition en ne gardant que ce qu'il y a avant le "-"
df_matches["edition"] = df_matches["edition"].str.split("-").str[0]
df_matches = df_matches.drop(columns='venue')
df_matches.head(3)

,edition,round,home_team,away_team,date,home_result,away_result,result,city
0,1930,Poules,France,Mexico (México),1930,4,1,home_team,Montevideo
1,1930,Poules,USA,Belgium (België),1930,3,0,home_team,Montevideo
2,1930,Poules,Yugoslavia (Југославија),Brazil (Brasil),1930,2,1,home_team,Montevideo

In [48]:
# On met une majuscule a chaque debut de mots
df_matches["city"] = df_matches["city"].str.title()

In [49]:
df_matches["home_team"].value_counts()

home_team
Brazil (Brasil)                71
Italy (Italia)                 56
Argentina                      47
FRG (BRD / Westdeutschland)    45
England                        35
                               ..
Iran (ایران)                    1
Ukraine (Україна)               1
Serbia (Србија)                 1
New Zealand (Aotearoa)          1
Ivory Coast (Côte d’Ivoire)     1
Name: count, Length: 77, dtype: int64

In [50]:
# regex pour enlever les noms d'origine des pays entre () : 
#test 
import re
test = "New Zealand (Aotearoa)"
re.findall(r"^[^(]+", test)

['New Zealand ']

In [51]:
df_matches["home_team"] = df_matches["home_team"].str.extract(r"^([^(]+)")
df_matches["home_team"].value_counts()

home_team
Brazil          71
Italy           56
Argentina       47
FRG             45
England         35
                ..
China            1
Iran             1
Ukraine          1
Serbia           1
New Zealand      1
Name: count, Length: 76, dtype: int64

In [52]:
df_matches["away_team"] = df_matches["away_team"].str.extract(r"^([^(]+)")

In [53]:
df_matches.sample(10)

,edition,round,home_team,away_team,date,home_result,away_result,result,city
455,1962,Poules,Soviet Union,Yugoslavia,1962,2,0,home_team,Arica
2476,1990,Huitièmes de finale,Ireland,Romania,1990,0,0,draw,Genova
469,1962,Poules,Brazil,Spain,1962,2,1,home_team,Viña Del Mar
3011,1994,Poules,USA,Romania,1994,0,1,away_home,Los Angeles
6363,2010,Poules,Ivory Coast,Portugal,2010,0,0,draw,Port_Elizabeth
343,1958,Poules,France,Scotland,1958,2,1,home_team,Örebro
4547,2002,Poules,Italy,Croatia,2002,1,2,away_home,Ibaraki
1730,1982,Poules,Belgium,Hungary,1982,1,1,draw,Elche
1388,1978,Demi-finales,Argentina,Poland,1978,2,0,home_team,Rosario
5497,2006,Finale,Italy,France,2006,1,1,draw,Berlin

In [54]:
df_matches["city"].value_counts()

city
México Df       23
Paris           21
Montevideo      18
Guadalajara     17
Johannesburg    15
                ..
Recife           1
Eskilstuna       1
Uddevalla        1
Örebro           1
Lille            1
Name: count, Length: 143, dtype: int64

In [55]:
# On retire les potentiels espaces 
df_matches["home_team"].str.strip()
df_matches["away_team"].str.strip()
df_matches["city"].str.strip()

0           Montevideo
1           Montevideo
2           Montevideo
3           Montevideo
4           Montevideo
             ...
6410      Johannesburg
6411         Cape Town
6412            Durban
6413    Port_Elizabeth
6414      Johannesburg
Name: city, Length: 772, dtype: object

In [57]:
type(df_matches['date'])

pandas.core.series.Series

In [ ]:
df_matches['date'] = df_matches['date'].astype(str) + '-01-01'
df_matches['date'] = pd.to_datetime(df_matches['date']).dt.date

DateParseError: Unknown datetime string format, unable to parse: 0       1930
1       1930
2       1930
3       1930
4       1930
        ...
6410    2010
6411    2010
6412    2010
6413    2010
6414    2010
Name: date, Length: 772, dtype: int64-01-01, at position 0

In [ ]:
df_matches.head(10)

,edition,round,home_team,away_team,date,home_result,away_result,result,city
0,1930,Poules,France,Mexico,1930,4,1,home_team,Montevideo
1,1930,Poules,USA,Belgium,1930,3,0,home_team,Montevideo
2,1930,Poules,Yugoslavia,Brazil,1930,2,1,home_team,Montevideo
3,1930,Poules,Romania,Peru,1930,3,1,home_team,Montevideo
4,1930,Poules,Argentina,France,1930,1,0,home_team,Montevideo
5,1930,Poules,Chile,Mexico,1930,3,0,home_team,Montevideo
6,1930,Poules,Yugoslavia,Bolivia,1930,4,0,home_team,Montevideo
7,1930,Poules,USA,Paraguay,1930,3,0,home_team,Montevideo
8,1930,Poules,Uruguay,Peru,1930,1,0,home_team,Montevideo
9,1930,Poules,Chile,France,1930,1,0,home_team,Montevideo

In [ ]:
df_matches.to_csv("./data/clean_1930-2010.csv", index=False)