In [162]:
import json
import pandas as pd
with open("data/data_2018.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [163]:
data

{'stadiums': [{'id': 1,
   'name': 'Luzhniki Stadium',
   'city': 'Moscow',
   'lat': 55.715765,
   'lng': 37.5515217,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Luzhniki_Stadium%2C_Moscow.jpg'},
  {'id': 2,
   'name': 'Otkrytiye Arena',
   'city': 'Moscow',
   'lat': 55.817765,
   'lng': 37.440363,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/5/50/Stadium_Spartak_in_Moscow.jpg'},
  {'id': 3,
   'name': 'Krestovsky Stadium',
   'city': 'Saint Petersburg',
   'lat': 59.97274,
   'lng': 30.221408,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Spb_06-2017_img40_Krestovsky_Stadium.jpg'},
  {'id': 4,
   'name': 'Kaliningrad Stadium',
   'city': 'Kaliningrad',
   'lat': 54.698157,
   'lng': 20.533859,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Kaliningrad_stadium_-_2018-04-07.jpg'},
  {'id': 5,
   'name': 'Kazan Arena',
   'city': 'Kazan',
   'lat': 55.820983,
   'lng': 49.160966,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Kazan_Arena_08-2016.jpg'},
  {'id': 6,
   'name': 'Nizhny Novgorod Stadium',
   'city': 'Nizhny Novgorod',
   'lat': 56.337287,
   'lng': 43.963251,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/9/90/Nizhny_Novgorod_Stadium_%28March_2018%29.jpg'},
  {'id': 7,
   'name': 'Cosmos Arena',
   'city': 'Samara',
   'lat': 53.278146,
   'lng': 50.238854,
   'image': 'http://img.fifa.com/image/upload/t_l4/d0mymt1ubl2pypmu3gn3.jpg'},
  {'id': 8,
   'name': 'Volgograd Arena',
   'city': 'Volgograd',
   'lat': 48.734195,
   'lng': 44.548345,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/6/61/Construction_of_Volgograd_Arena_inside_04.jpg'},
  {'id': 9,
   'name': 'Mordovia Arena',
   'city': 'Saransk',
   'lat': 54.181795,
   'lng': 45.203851,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/4/45/Match_at_Mordovia_Arena_stadium.jpg'},
  {'id': 10,
   'name': 'Rostov Arena',
   'city': 'Rostov-on-Don',
   'lat': 47.209581,
   'lng': 39.738424,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/9/94/Rostov-Arens_%28april_2018%29_01.jpg'},
  {'id': 11,
   'name': 'Fisht Olympic Stadium',
   'city': 'Sochi',
   'lat': 43.402011,
   'lng': 39.955709,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/5/55/Fisht_Stadium_in_January_2018.jpg'},
  {'id': 12,
   'name': 'Central Stadium',
   'city': 'Yekaterinburg',
   'lat': 56.83249,
   'lng': 60.573585,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Estadio_Central_%28Ekaterinburg-arena%29.jpg'}],
 'tvchannels': [{'id': 1,
   'name': 'DR1',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/8/88/DR1_logo_2013.svg',
   'country': 'Denmark',
   'iso2': 'dk',
   'lang': ['da']},
  {'id': 2,
   'name': 'TV2',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/8/85/Danish_TV_2_logo.png',
   'country': 'Denmark',
   'iso2': 'dk',
   'lang': ['da']},
  {'id': 3,
   'name': 'BBC UK',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/e/eb/BBC.svg',
   'country': 'UK',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 4,
   'name': 'ITV UK',
   'icon': 'https://upload.wikimedia.org/wikipedia/en/9/92/ITV_logo_2013.svg',
   'country': 'UK',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 5,
   'name': 'ITV4 UK',
   'icon': 'https://upload.wikimedia.org/wikipedia/en/9/92/ITV_logo_2013.svg',
   'country': 'UK',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 6,
   'name': 'Cuatro',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Logotipo_de_Cuatro.svg',
   'country': 'Spain',
   'iso2': 'es',
   'lang': ['es']},
  {'id': 7,
   'name': 'Telecinco',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/7/75/Telecinco_2012.png',
   'country': 'Spain',
   'iso2': 'es',
   'lang': ['es']},
  {'id': 8,
   'name': 'Globo',
   'icon': 'https://upload.wikimedia.org/wikipedia/pt/2/22/Logotipo_da_Rede_Globo.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 9,
   'name': 'SportTV',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/SporTV_2017_logo.svg/692px-SporTV_2017_logo.svg.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 10,
   'name': 'SportTV2',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/SporTV_2_2017_logo.svg/664px-SporTV_2_2017_logo.svg.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 11,
   'name': 'SportTV3',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/SporTV_3_2017_logo.svg/703px-SporTV_3_2017_logo.svg.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 12,
   'name': 'Sony Ten',
   'icon': 'https://upload.wikimedia.org/wikipedia/en/5/5f/Sony_TEN_logo.png',
   'country': 'India',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 13,
   'name': 'Fox',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/2/25/FOX_wordmark.svg',
   'country': 'USA',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 14,
   'name': 'FS1',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/3/37/2015_Fox_Sports_1_logo.svg',
   'country': 'USA',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 15,
   'name': 'TransTV',
   'icon': 'https://upload.wikimedia.org/wikipedia/id/6/62/Trans_TV_2013.svg',
   'country': 'Indonesia',
   'iso2': 'id',
   'lang': ['id']},
  {'id': 16,
   'name': 'Trans7',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Trans_7_2013_Iklan.svg',
   'country': 'Indonesia',
   'iso2': 'id',
   'lang': ['id']},
  {'id': 17,
   'name': 'ARD',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/6/68/ARD_logo.svg',
   'country': 'Germany',
   'iso2': 'de',
   'lang': ['de']},
  {'id': 18,
   'name': 'ZDF',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/c/c1/ZDF_logo.svg',
   'country': 'Germany',
   'iso2': 'de',
   'lang': ['de']},
  {'id': 19,
   'name': 'ONE',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/1/16/One_TV_Logo.svg',
   'country': 'Germany',
   'iso2': 'de',
   'lang': ['de']},
  {'id': 20,
   'name': 'TVP 1',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/TVP1_logo.svg/2000px-TVP1_logo.svg.png',
   'country': 'Poland',
   'iso2': 'pl',
   'lang': ['pl']},
  {'id': 21,
   'name': 'TVP 2',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/TVP2_logo.svg/2000px-TVP2_logo.svg.png',
   'country': 'Poland',
   'iso2': 'pl',
   'lang': ['pl']},
  {'id': 22,
   'name': 'TVP SPORT',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/7/76/NewTVP_SPORT.png',
   'country': 'Poland',
   'iso2': 'pl',
   'lang': ['pl']}],
 'teams': [{'id': 1,
   'name': 'Russia',
   'fifaCode': 'RUS',
   'iso2': 'ru',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/900px-Flag_of_Russia.png',
   'emoji': 'flag-ru',
   'emojiString': '🇷🇺'},
  {'id': 2,
   'name': 'Saudi Arabia',
   'fifaCode': 'KSA',
   'iso2': 'sa',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/750px-Flag_of_Saudi_Arabia.png',
   'emoji': 'flag-sa',
   'emojiString': '🇸🇦'},
  {'id': 3,
   'name': 'Egypt',
   'fifaCode': 'EGY',
   'iso2': 'eg',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/900px-Flag_of_Egypt.png',
   'emoji': 'flag-eg',
   'emojiString': '🇪🇬'},
  {'id': 4,
   'name': 'Uruguay',
   'fifaCode': 'URU',
   'iso2': 'uy',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/900px-Flag_of_Uruguay.png',
   'emoji': 'flag-uy',
   'emojiString': '🇺🇾'},
  {'id': 5,
   'name': 'Portugal',
   'fifaCode': 'POR',
   'iso2': 'pt',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/600px-Flag_of_Portugal.png',
   'emoji': 'flag-pt',
   'emojiString': '🇵🇹'},
  {'id': 6,
   'name': 'Spain',
   'fifaCode': 'ESP',
   'iso2': 'es',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/750px-Flag_of_Spain.png',
   'emoji': 'flag-es',
   'emojiString': '🇪🇸'},
  {'id': 7,
   'name': 'Morocco',
   'fifaCode': 'MAR',
   'iso2': 'ma',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/900px-Flag_of_Morocco.png',
   'emoji': 'flag-ma',
   'emojiString': '🇲🇦'},
  {'id': 8,
   'name': 'Iran',
   'fifaCode': 'IRN',
   'iso2': 'ir',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/630px-Flag_of_Iran.png',
   'emoji': 'flag-ir',
   'emojiString': '🇮🇷'},
  {'id': 9,
   'name': 'France',
   'fifaCode': 'FRA',
   'iso2': 'fr',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/900px-Flag_of_France.png',
   'emoji': 'flag-fr',
   'emojiString': '🇫🇷'},
  {'id': 10,
   'name': 'Australia',
   'fifaCode': 'AUS',
   'iso2': 'au',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1280px-Flag_of_Australia_%28converted%29.png',
   'emoji': 'flag-au',
   'emojiString': '🇦🇺'},
  {'id': 11,
   'name': 'Peru',
   'fifaCode': 'PER',
   'iso2': 'pe',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Peru_%28state%29.svg/900px-Flag_of_Peru_%28state%29.png',
   'emoji': 'flag-pe',
   'emojiString': '🇵🇪'},
  {'id': 12,
   'name': 'Denmark',
   'fifaCode': 'DEN',
   'iso2': 'dk',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/740px-Flag_of_Denmark.png',
   'emoji': 'flag-dk',
   'emojiString': '🇩🇰'},
  {'id': 13,
   'name': 'Argentina',
   'fifaCode': 'ARG',
   'iso2': 'ar',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/800px-Flag_of_Argentina.png',
   'emoji': 'flag-ar',
   'emojiString': '🇦🇷'},
  {'id': 14,
   'name': 'Iceland',
   'fifaCode': 'ISL',
   'iso2': 'is',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/800px-Flag_of_Iceland.png',
   'emoji': 'flag-is',
   'emojiString': '🇮🇸'},
  {'id': 15,
   'name': 'Croatia',
   'fifaCode': 'CRO',
   'iso2': 'hr',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/800px-Flag_of_Croatia.png',
   'emoji': 'flag-hr',
   'emojiString': '🇭🇷'},
  {'id': 16,
   'name': 'Nigeria',
   'fifaCode': 'NGA',
   'iso2': 'ng',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/800px-Flag_of_Nigeria.png',
   'emoji': 'flag-ng',
   'emojiString': '🇳🇬'},
  {'id': 17,
   'name': 'Brazil',
   'fifaCode': 'BRA',
   'iso2': 'br',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/720px-Flag_of_Brazil.png',
   'emoji': 'flag-br',
   'emojiString': '🇧🇷'},
  {'id': 18,
   'name': 'Switzerland',
   'fifaCode': 'SUI',
   'iso2': 'ch',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/320px-Flag_of_Switzerland_%28Pantone%29.png',
   'emoji': 'flag-ch',
   'emojiString': '🇨🇭'},
  {'id': 19,
   'name': 'Costa Rica',
   'fifaCode': 'CRC',
   'iso2': 'cr',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/833px-Flag_of_Costa_Rica_%28state%29.png',
   'emoji': 'flag-cr',
   'emojiString': '🇨🇷'},
  {'id': 20,
   'name': 'Serbia',
   'fifaCode': 'SRB',
   'iso2': 'rs',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1350px-Flag_of_Serbia.png',
   'emoji': 'flag-rs',
   'emojiString': '🇷🇸'},
  {'id': 21,
   'name': 'Germany',
   'fifaCode': 'GER',
   'iso2': 'de',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/800px-Flag_of_Germany.png',
   'emoji': 'flag-de',
   'emojiString': '🇩🇪'},
  {'id': 22,
   'name': 'Mexico',
   'fifaCode': 'MEX',
   'iso2': 'mx',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/800px-Flag_of_Mexico.png',
   'emoji': 'flag-mx',
   'emojiString': '🇲🇽'},
  {'id': 23,
   'name': 'Sweden',
   'fifaCode': 'SWE',
   'iso2': 'se',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/1600px-Flag_of_Sweden.png',
   'emoji': 'flag-se',
   'emojiString': '🇸🇪'},
  {'id': 24,
   'name': 'South Korea',
   'fifaCode': 'KOR',
   'iso2': 'kr',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/900px-Flag_of_South_Korea.png',
   'emoji': 'flag-kr',
   'emojiString': '🇰🇷'},
  {'id': 25,
   'name': 'Belgium',
   'fifaCode': 'BEL',
   'iso2': 'be',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/450px-Flag_of_Belgium.png',
   'emoji': 'flag-be',
   'emojiString': '🇧🇪'},
  {'id': 26,
   'name': 'Panama',
   'fifaCode': 'PAN',
   'iso2': 'pa',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/450px-Flag_of_Panama.png',
   'emoji': 'flag-pa',
   'emojiString': '🇵🇦'},
  {'id': 27,
   'name': 'Tunisia',
   'fifaCode': 'TUN',
   'iso2': 'tn',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1200px-Flag_of_Tunisia.png',
   'emoji': 'flag-tn',
   'emojiString': '🇹🇳'},
  {'id': 28,
   'name': 'England',
   'fifaCode': 'ENG',
   'iso2': 'gb-eng',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/800px-Flag_of_England.png',
   'emoji': 'flag-england',
   'emojiString': '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f'},
  {'id': 29,
   'name': 'Poland',
   'fifaCode': 'POL',
   'iso2': 'pl',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1280px-Flag_of_Poland.png',
   'emoji': 'flag-pl',
   'emojiString': '🇵🇱'},
  {'id': 30,
   'name': 'Senegal',
   'fifaCode': 'SEN',
   'iso2': 'sn',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/900px-Flag_of_Senegal.svg.png',
   'emoji': 'flag-sn',
   'emojiString': '🇸🇳'},
  {'id': 31,
   'name': 'Colombia',
   'fifaCode': 'COL',
   'iso2': 'co',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/450px-Flag_of_Colombia.png',
   'emoji': 'flag-co',
   'emojiString': '🇨🇴'},
  {'id': 32,
   'name': 'Japan',
   'fifaCode': 'JPN',
   'iso2': 'jp',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/900px-Flag_of_Japan.png',
   'emoji': 'flag-jp',
   'emojiString': '🇯🇵'}],
 'groups': {'a': {'name': 'Group A',
   'winner': 4,
   'runnerup': 1,
   'matches': [{'name': 1,
     'type': 'group',
     'home_team': 1,
     'away_team': 2,
     'home_result': 5,
     'away_result': 0,
     'date': '2018-06-14T18:00:00+03:00',
     'stadium': 1,
     'channels': [4, 6, 13, 17, 20, 22],
     'finished': True,
     'matchday': 1},
    {'name': 2,
     'type': 'group',
     'home_team': 3,
     'away_team': 4,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-15T17:00:00+05:00',
     'stadium': 12,
     'channels': [3, 6, 14, 17, 20, 22],
     'finished': True,
     'matchday': 1},
    {'name': 17,
     'type': 'group',
     'home_team': 1,
     'away_team': 3,
     'home_result': 3,
     'away_result': 1,
     'date': '2018-06-19T21:00:00+03:00',
     'stadium': 3,
     'channels': [3, 6, 13, 17, 15, 21, 22],
     'finished': True,
     'matchday': 2},
    {'name': 18,
     'type': 'group',
     'home_team': 4,
     'away_team': 2,
     'home_result': 1,
     'away_result': 0,
     'date': '2018-06-20T18:00:00+03:00',
     'stadium': 10,
     'channels': [3, 6, 13, 17, 21, 22],
     'finished': True,
     'matchday': 2},
    {'name': 33,
     'type': 'group',
     'home_team': 4,
     'away_team': 1,
     'home_result': 3,
     'away_result': 0,
     'date': '2018-06-25T18:00:00+04:00',
     'stadium': 7,
     'channels': [4, 6, 13, 18, 15, 20, 22],
     'finished': True,
     'matchday': 3},
    {'name': 34,
     'type': 'group',
     'home_team': 2,
     'away_team': 3,
     'home_result': 2,
     'away_result': 1,
     'date': '2018-06-25T17:00:00+03:00',
     'stadium': 8,
     'channels': [5, 6, 14, 18, 15, 21, 22],
     'finished': True,
     'matchday': 3}]},
  'b': {'name': 'Group B',
   'winner': 6,
   'runnerup': 5,
   'matches': [{'name': 3,
     'type': 'group',
     'home_team': 5,
     'away_team': 6,
     'home_result': 3,
     'away_result': 3,
     'date': '2018-06-15T21:00:00+03:00',
     'stadium': 11,
     'channels': [3, 7, 13, 15, 17, 20, 22],
     'finished': True,
     'matchday': 1},
    {'name': 4,
     'type': 'group',
     'home_team': 7,
     'away_team': 8,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-15T18:00:00+03:00',
     'stadium': 3,
     'channels': [4, 6, 13, 17, 21, 22],
     'finished': True,
     'matchday': 1},
    {'name': 19,
     'type': 'group',
     'home_team': 5,
     'away_team': 7,
     'home_result': 1,
     'away_result': 0,
     'date': '2018-06-20T15:00:00+03:00',
     'stadium': 1,
     'channels': [3, 6, 14, 15, 17, 20, 22],
     'finished': True,
     'matchday': 2},
    {'name': 20,
     'type': 'group',
     'home_team': 8,
     'away_team': 6,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-20T21:00:00+03:00',
     'stadium': 5,
     'channels': [4, 7, 13, 15, 17, 20, 21],
     'finished': True,
     'matchday': 2},
    {'name': 35,
     'type': 'group',
     'home_team': 8,
     'away_team': 5,
     'home_result': 1,
     'away_result': 1,
     'date': '2018-06-25T21:00:00+03:00',
     'stadium': 9,
     'channels': [3, 6, 13, 18, 21, 22],
     'finished': True,
     'matchday': 3},
    {'name': 36,
     'type': 'group',
     'home_team': 6,
     'away_team': 7,
     'home_result': 2,
     'away_result': 2,
     'date': '2018-06-25T20:00:00+02:00',
     'stadium': 4,
     'channels': [3, 7, 14, 18, 21, 22],
     'finished': True,
     'matchday': 3}]},
  'c': {'name': 'Group C',
   'winner': 9,
   'runnerup': 12,
   'matches': [{'name': 5,
     'type': 'group',
     'home_team': 9,
     'away_team': 10,
     'home_result': 2,
     'away_result': 1,
     'date': '2018-06-16T13:00:00+03:00',
     'stadium': 5,
     'channels': [3, 6, 14, 15, 18, 21, 22],
     'finished': True,
     'matchday': 1},
    {'name': 6,
     'type': 'group',
     'home_team': 11,
     'away_team': 12,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-16T19:00:00+03:00',
     'stadium': 9,
     'channels': [3, 6, 14, 15, 18, 21, 22],
     'finished': True,
     'matchday': 1},
    {'name': 21,
     'type': 'group',
     'home_team': 9,
     'away_team': 11,
     'home_result': 1,
     'away_result': 0,
     'date': '2018-06-21T20:00:00+05:00',
     'stadium': 12,
     'channels': [4, 6, 13, 15, 18, 21, 22],
     'finished': True,
     'matchday': 2},
    {'name': 22,
     'type': 'group',
     'home_team': 12,
     'away_team': 10,
     'home_result': 1,
     'away_result': 1,
     'date': '2018-06-21T16:00:00+04:00',
     'stadium': 7,
     'channels': [4, 6, 14, 15, 18, 20, 22],
     'finished': True,
     'matchday': 2},
    {'name': 37,
     'type': 'group',
     'home_team': 12,
     'away_team': 9,
     'home_result': 0,
     'away_result': 0,
     'date': '2018-06-26T17:00:00+03:00',
     'stadium': 1,
     'channels': [4, 6, 13, 15, 17, 20, 22],
     'finished': True,
     'matchday': 3},
    {'name': 38,
     'type': 'group',
     'home_team': 10,
     'away_team': 11,
     'home_result': 0,
     'away_result': 2,
     'date': '2018-06-26T17:00:00+03:00',
     'stadium': 11,
     'channels': [5, 6, 14, 16, 19, 21, 22],
     'finished': True,
     'matchday': 3}]},
  'd': {'name': 'Group D',
   'winner': 15,
   'runnerup': 13,
   'matches': [{'name': 7,
     'type': 'group',
     'home_team': 13,
     'away_team': 14,
     'home_result': 1,
     'away_result': 1,
     'date': '2018-06-16T16:00:00+03:00',
     'stadium': 2,
     'channels': [4, 6, 13, 18, 20, 22],

In [164]:
# Le json a 5 clés 
data.keys()

dict_keys(['stadiums', 'tvchannels', 'teams', 'groups', 'knockout'])

In [165]:
#1er dictionnaire : stadium (utile pour recuperer le nom des villes)
df_stadiums = pd.DataFrame(data["stadiums"])
df_stadiums

,id,name,city,lat,lng,image
0,1,Luzhniki Stadium,Moscow,55.715765,37.551522,https://upload.wikimedia.org/wikipedia/commons...
1,2,Otkrytiye Arena,Moscow,55.817765,37.440363,https://upload.wikimedia.org/wikipedia/commons...
2,3,Krestovsky Stadium,Saint Petersburg,59.972740,30.221408,https://upload.wikimedia.org/wikipedia/commons...
3,4,Kaliningrad Stadium,Kaliningrad,54.698157,20.533859,https://upload.wikimedia.org/wikipedia/commons...
4,5,Kazan Arena,Kazan,55.820983,49.160966,https://upload.wikimedia.org/wikipedia/commons...
5,6,Nizhny Novgorod Stadium,Nizhny Novgorod,56.337287,43.963251,https://upload.wikimedia.org/wikipedia/commons...
6,7,Cosmos Arena,Samara,53.278146,50.238854,http://img.fifa.com/image/upload/t_l4/d0mymt1u...
7,8,Volgograd Arena,Volgograd,48.734195,44.548345,https://upload.wikimedia.org/wikipedia/commons...
8,9,Mordovia Arena,Saransk,54.181795,45.203851,https://upload.wikimedia.org/wikipedia/commons...
9,10,Rostov Arena,Rostov-on-Don,47.209581,39.738424,https://upload.wikimedia.org/wikipedia/commons...
10,11,Fisht Olympic Stadium,Sochi,43.402011,39.955709,https://upload.wikimedia.org/wikipedia/commons...
11,12,Central Stadium,Yekaterinburg,56.832490,60.573585,https://upload.wikimedia.org/wikipedia/commons...

In [166]:
df_stadiums = df_stadiums[["id", "city"]]
df_stadiums

    id              city
0    1            Moscow
1    2            Moscow
2    3  Saint Petersburg
3    4       Kaliningrad
4    5             Kazan
5    6   Nizhny Novgorod
6    7            Samara
7    8         Volgograd
8    9           Saransk
9   10     Rostov-on-Don
10  11             Sochi
11  12     Yekaterinburg

In [167]:
#2eme dictionnaire : Tvchannels  
df_tvchannels = pd.DataFrame(data["tvchannels"])
df_tvchannels.head(1)

,id,name,icon,country,iso2,lang
0,1,DR1,https://upload.wikimedia.org/wikipedia/commons...,Denmark,dk,[da]

In [168]:
#3e dictionnaire : Teams (utile pour récuperer le nom des villes participantes) 
df_teams = pd.DataFrame(data["teams"])
df_teams.head(3)

,id,name,fifaCode,iso2,flag,emoji,emojiString
0,1,Russia,RUS,ru,https://upload.wikimedia.org/wikipedia/en/thum...,flag-ru,🇷🇺
1,2,Saudi Arabia,KSA,sa,https://upload.wikimedia.org/wikipedia/commons...,flag-sa,🇸🇦
2,3,Egypt,EGY,eg,https://upload.wikimedia.org/wikipedia/commons...,flag-eg,🇪🇬

In [169]:
df_teams = df_teams[["id", "name"]]
df_teams

    id          name
0    1        Russia
1    2  Saudi Arabia
2    3         Egypt
3    4       Uruguay
4    5      Portugal
5    6         Spain
6    7       Morocco
7    8          Iran
8    9        France
9   10     Australia
10  11          Peru
11  12       Denmark
12  13     Argentina
13  14       Iceland
14  15       Croatia
15  16       Nigeria
16  17        Brazil
17  18   Switzerland
18  19    Costa Rica
19  20        Serbia
20  21       Germany
21  22        Mexico
22  23        Sweden
23  24   South Korea
24  25       Belgium
25  26        Panama
26  27       Tunisia
27  28       England
28  29        Poland
29  30       Senegal
30  31      Colombia
31  32         Japan

In [170]:
#4e dictionnaire : Groups  (poules) -> dictionnaires imbriqués  
data["groups"]
data["groups"].keys()

dict_keys(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [171]:
groups = ["a", "b", "c", "d", "e", "f", "g", "h"]

liste = []
for i in groups : 
    df = pd.DataFrame(data["groups"][i]["matches"])
    df["groups"] = i
    liste.append(df)


df_groups = pd.concat(liste)
df_groups

,name,type,home_team,away_team,home_result,away_result,date,stadium,channels,finished,matchday,groups
0,1,group,1,2,5,0,2018-06-14T18:00:00+03:00,1,"[4, 6, 13, 17, 20, 22]",True,1,a
1,2,group,3,4,0,1,2018-06-15T17:00:00+05:00,12,"[3, 6, 14, 17, 20, 22]",True,1,a
2,17,group,1,3,3,1,2018-06-19T21:00:00+03:00,3,"[3, 6, 13, 17, 15, 21, 22]",True,2,a
3,18,group,4,2,1,0,2018-06-20T18:00:00+03:00,10,"[3, 6, 13, 17, 21, 22]",True,2,a
4,33,group,4,1,3,0,2018-06-25T18:00:00+04:00,7,"[4, 6, 13, 18, 15, 20, 22]",True,3,a
5,34,group,2,3,2,1,2018-06-25T17:00:00+03:00,8,"[5, 6, 14, 18, 15, 21, 22]",True,3,a
0,3,group,5,6,3,3,2018-06-15T21:00:00+03:00,11,"[3, 7, 13, 15, 17, 20, 22]",True,1,b
1,4,group,7,8,0,1,2018-06-15T18:00:00+03:00,3,"[4, 6, 13, 17, 21, 22]",True,1,b
2,19,group,5,7,1,0,2018-06-20T15:00:00+03:00,1,"[3, 6, 14, 15, 17, 20, 22]",True,2,b
3,20,group,8,6,0,1,2018-06-20T21:00:00+03:00,5,"[4, 7, 13, 15, 17, 20, 21]",True,2,b
4,35,group,8,5,1,1,2018-06-25T21:00:00+03:00,9,"[3, 6, 13, 18, 21, 22]",True,3,b
5,36,group,6,7,2,2,2018-06-25T20:00:00+02:00,4,"[3, 7, 14, 18, 21, 22]",True,3,b
0,5,group,9,10,2,1,2018-06-16T13:00:00+03:00,5,"[3, 6, 14, 15, 18, 21, 22]",True,1,c
1,6,group,11,12,0,1,2018-06-16T19:00:00+03:00,9,"[3, 6, 14, 15, 18, 21, 22]",True,1,c
2,21,group,9,11,1,0,2018-06-21T20:00:00+05:00,12,"[4, 6, 13, 15, 18, 21, 22]",True,2,c
3,22,group,12,10,1,1,2018-06-21T16:00:00+04:00,7,"[4, 6, 14, 15, 18, 20, 22]",True,2,c
4,37,group,12,9,0,0,2018-06-26T17:00:00+03:00,1,"[4, 6, 13, 15, 17, 20, 22]",True,3,c
5,38,group,10,11,0,2,2018-06-26T17:00:00+03:00,11,"[5, 6, 14, 16, 19, 21, 22]",True,3,c
0,7,group,13,14,1,1,2018-06-16T16:00:00+03:00,2,"[4, 6, 13, 18, 20, 22]",True,1,d
1,8,group,15,16,2,0,2018-06-16T21:00:00+02:00,4,"[4, 6, 14, 18, 15, 20, 22]",True,1,d
2,23,group,13,15,0,3,2018-06-21T21:00:00+03:00,6,"[3, 6, 13, 18, 20, 22]",True,2,d
3,24,group,16,14,2,0,2018-06-22T18:00:00+03:00,8,"[3, 6, 13, 18, 15, 21, 22]",True,2,d
4,39,group,16,13,1,2,2018-06-26T21:00:00+03:00,3,"[3, 6, 13, 15, 17, 20, 22]",True,3,d
5,40,group,14,15,1,2,2018-06-26T21:00:00+03:00,10,"[3, 6, 14, 17, 21, 22]",True,3,d
0,9,group,17,18,1,1,2018-06-17T21:00:00+03:00,10,"[4, 6, 14, 18, 20, 22]",True,1,e
1,10,group,19,20,0,1,2018-06-17T16:00:00+04:00,7,"[4, 6, 13, 18, 20, 22]",True,1,e
2,25,group,17,19,2,0,2018-06-22T15:00:00+03:00,3,"[4, 6, 14, 18, 15, 20, 22]",True,2,e
3,26,group,20,18,1,2,2018-06-22T20:00:00+02:00,4,"[3, 6, 13, 18, 15, 20, 22]",True,2,e
4,41,group,20,17,0,2,2018-06-27T21:00:00+03:00,2,"[4, 6, 13, 18, 15, 20, 22]",True,3,e
5,42,group,18,19,2,2,2018-06-27T21:00:00+03:00,6,"[5, 6, 14, 18, 15, 21, 22]",True,3,e
0,11,group,21,22,0,1,2018-06-17T18:00:00+03:00,1,"[3, 6, 14, 18, 21, 22]",True,1,f
1,12,group,23,24,1,0,2018-06-18T15:00:00+03:00,6,"[4, 6, 14, 17, 20, 22]",True,1,f
2,27,group,21,23,2,1,2018-06-23T21:00:00+03:00,11,"[4, 6, 13, 15, 17, 20, 22]",True,2,f
3,28,group,24,22,1,2,2018-06-23T18:00:00+03:00,10,"[4, 6, 13, 15, 17, 21, 22]",True,2,f
4,43,group,24,21,2,0,2018-06-27T17:00:00+03:00,5,"[3, 6, 14, 18, 15, 20, 22]",True,3,f
5,44,group,22,23,0,3,2018-06-27T19:00:00+05:00,12,"[3, 6, 13, 18, 21, 22]",True,3,f
0,13,group,25,26,3,0,2018-06-18T18:00:00+03:00,11,"[3, 6, 14, 17, 21, 22]",True,1,g
1,14,group,27,28,1,2,2018-06-18T21:00:00+03:00,8,"[3, 6, 14, 17, 20, 22]",True,1,g
2,29,group,25,27,5,2,2018-06-23T15:00:00+03:00,2,"[3, 6, 13, 15, 17, 20, 22]",True,2,g
3,30,group,28,26,6,1,2018-06-24T15:00:00+03:00,6,"[3, 6, 14, 15, 17, 20, 22]",True,2,g
4,45,group,28,25,0,1,2018-06-28T20:00:00+02:00,4,"[4, 6, 13, 15, 17, 20, 22]",True,3,g
5,46,group,26,27,1,2,2018-06-28T21:00:00+03:00,9,"[5, 6, 14, 19, 16, 21, 22]",True,3,g
0,15,group,29,30,1,2,2018-06-19T18:00:00+03:00,2,"[4, 6, 13, 18, 15, 20, 22]",True,1,h
1,16,group,31,32,1,2,2018-06-19T15:00:00+03:00,9,"[3, 6, 14, 18, 20, 22]",True,1,h
2,31,group,29,31,0,3,2018-06-24T20:00:00+02:00,5,"[4, 6, 13, 15, 17, 20, 22]",True,2,h
3,32,group,32,30,2,2,2018-06-24T18:00:00+03:00,12,"[3, 6, 13, 15, 17, 20, 22]",True,2,h
4,47,group,32,29,0,1,2018-06-28T17:00:00+03:00,8,"[3, 6, 14, 15, 17, 20, 22]",True,3,h
5,48,group,30,31,0,1,2018-06-28T18:00:00+04:00,7,"[3, 6, 13, 17, 21, 22]",True,3,h

In [172]:
#5e dictionnaire : Knockout (type de matches) -> dictionnaires imbriqués  
data["knockout"]

{'round_16': {'name': 'Round of 16',
  'matches': [{'name': 49,
    'type': 'qualified',
    'home_team': 4,
    'away_team': 5,
    'home_result': 2,
    'away_result': 1,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 4,
    'date': '2018-06-30T21:00:00+03:00',
    'stadium': 11,
    'channels': [4, 13, 15],
    'finished': True,
    'matchday': 4},
   {'name': 50,
    'type': 'qualified',
    'home_team': 9,
    'away_team': 13,
    'home_result': 4,
    'away_result': 3,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 9,
    'date': '2018-06-30T17:00:00+03:00',
    'stadium': 5,
    'channels': [4, 6, 13, 15],
    'finished': True,
    'matchday': 4},
   {'name': 51,
    'type': 'qualified',
    'home_team': 6,
    'away_team': 1,
    'home_result': 1,
    'away_result': 1,
    'home_penalty': 3,
    'away_penalty': 4,
    'winner': 1,
    'date': '2018-07-01T17:00:00+03:00',
    'stadium': 1,
    'channels': [3, 13, 15],
    'finished': True,
    'matchday': 4},
   {'name': 52,
    'type': 'qualified',
    'home_team': 15,
    'away_team': 12,
    'home_result': 1,
    'away_result': 1,
    'home_penalty': 3,
    'away_penalty': 2,
    'winner': 15,
    'date': '2018-07-01T21:00:00+03:00',
    'stadium': 6,
    'channels': [4, 6, 13, 15],
    'finished': True,
    'matchday': 4},
   {'name': 53,
    'type': 'qualified',
    'home_team': 17,
    'away_team': 22,
    'home_result': 2,
    'away_result': 0,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 17,
    'date': '2018-07-02T18:00:00+04:00',
    'stadium': 7,
    'channels': [3, 6, 14, 15],
    'finished': True,
    'matchday': 4},
   {'name': 54,
    'type': 'qualified',
    'home_team': 25,
    'away_team': 32,
    'home_result': 3,
    'away_result': 2,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 25,
    'date': '2018-07-02T21:00:00+03:00',
    'stadium': 10,
    'channels': [3, 6, 13, 16],
    'finished': True,
    'matchday': 4},
   {'name': 55,
    'type': 'qualified',
    'home_team': 23,
    'away_team': 18,
    'home_result': 1,
    'away_result': 0,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 23,
    'date': '2018-07-03T17:00:00+03:00',
    'stadium': 3,
    'channels': [4, 6, 14, 16],
    'finished': True,
    'matchday': 4},
   {'name': 56,
    'type': 'qualified',
    'home_team': 31,
    'away_team': 28,
    'home_result': 1,
    'away_result': 1,
    'home_penalty': 3,
    'away_penalty': 4,
    'winner': 28,
    'date': '2018-07-03T21:00:00+03:00',
    'stadium': 2,
    'channels': [3, 6, 13, 15],
    'finished': True,
    'matchday': 4}]},
 'round_8': {'name': 'Quarter-finals',
  'matches': [{'name': 57,
    'type': 'winner',
    'home_team': 4,
    'away_team': 9,
    'home_result': 0,
    'away_result': 2,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 9,
    'date': '2018-07-06T17:00:00+03:00',
    'stadium': 6,
    'channels': [3, 14, 15],
    'finished': True,
    'matchday': 5},
   {'name': 58,
    'type': 'winner',
    'home_team': 17,
    'away_team': 25,
    'home_result': 1,
    'away_result': 2,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 25,
    'date': '2018-07-06T21:00:00+03:00',
    'stadium': 5,
    'channels': [3, 14, 15],
    'finished': True,
    'matchday': 5},
   {'name': 59,
    'type': 'winner',
    'home_team': 1,
    'away_team': 15,
    'home_result': 2,
    'away_result': 2,
    'home_penalty': 3,
    'away_penalty': 4,
    'winner': 15,
    'date': '2018-07-07T21:00:00+03:00',
    'stadium': 11,
    'channels': [4, 13, 16],
    'finished': True,
    'matchday': 5},
   {'name': 60,
    'type': 'winner',
    'home_team': 23,
    'away_team': 28,
    'home_result': 0,
    'away_result': 2,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 28,
    'date': '2018-07-07T18:00:00+04:00',
    'stadium': 7,
    'channels': [4, 13, 16],
    'finished': True,
    'matchday': 5}]},
 'round_4': {'name': 'Semi-finals',
  'matches': [{'name': 61,
    'type': 'winner',
    'home_team': 9,
    'away_team': 25,
    'home_result': 1,
    'away_result': 0,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 9,
    'date': '2018-07-10T21:00:00+03:00',
    'stadium': 3,
    'channels': [4, 13, 16],
    'finished': True,
    'matchday': 6},
   {'name': 62,
    'type': 'winner',
    'home_team': 15,
    'away_team': 28,
    'home_result': 2,
    'away_result': 1,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 15,
    'date': '2018-07-11T21:00:00+03:00',
    'stadium': 1,
    'channels': [3, 13, 15],
    'finished': True,
    'matchday': 6}]},
 'round_2_loser': {'name': 'Third place play-off',
  'matches': [{'name': 63,
    'type': 'loser',
    'home_team': 25,
    'away_team': 28,
    'home_result': 2,
    'away_result': 0,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 25,
    'date': '2018-07-14T17:00:00+03:00',
    'stadium': 3,
    'channels': [4, 13, 15],
    'finished': True,
    'matchday': 7}]},
 'round_2': {'name': 'Final',
  'matches': [{'name': 64,
    'type': 'winner',
    'home_team': 9,
    'away_team': 15,
    'home_result': 4,
    'away_result': 2,
    'home_penalty': None,
    'away_penalty': None,
    'winner': 9,
    'date': '2018-07-15T18:00:00+03:00',
    'stadium': 1,
    'channels': [3, 4, 13, 15],
    'finished': True,
    'matchday': 7}]}}

In [173]:
data["knockout"].keys()
#Il y a 5 dictionnaires à l'interieur

dict_keys(['round_16', 'round_8', 'round_4', 'round_2_loser', 'round_2'])

In [174]:
data["knockout"]["round_16"]

{'name': 'Round of 16',
 'matches': [{'name': 49,
   'type': 'qualified',
   'home_team': 4,
   'away_team': 5,
   'home_result': 2,
   'away_result': 1,
   'home_penalty': None,
   'away_penalty': None,
   'winner': 4,
   'date': '2018-06-30T21:00:00+03:00',
   'stadium': 11,
   'channels': [4, 13, 15],
   'finished': True,
   'matchday': 4},
  {'name': 50,
   'type': 'qualified',
   'home_team': 9,
   'away_team': 13,
   'home_result': 4,
   'away_result': 3,
   'home_penalty': None,
   'away_penalty': None,
   'winner': 9,
   'date': '2018-06-30T17:00:00+03:00',
   'stadium': 5,
   'channels': [4, 6, 13, 15],
   'finished': True,
   'matchday': 4},
  {'name': 51,
   'type': 'qualified',
   'home_team': 6,
   'away_team': 1,
   'home_result': 1,
   'away_result': 1,
   'home_penalty': 3,
   'away_penalty': 4,
   'winner': 1,
   'date': '2018-07-01T17:00:00+03:00',
   'stadium': 1,
   'channels': [3, 13, 15],
   'finished': True,
   'matchday': 4},
  {'name': 52,
   'type': 'qualified',
   'home_team': 15,
   'away_team': 12,
   'home_result': 1,
   'away_result': 1,
   'home_penalty': 3,
   'away_penalty': 2,
   'winner': 15,
   'date': '2018-07-01T21:00:00+03:00',
   'stadium': 6,
   'channels': [4, 6, 13, 15],
   'finished': True,
   'matchday': 4},
  {'name': 53,
   'type': 'qualified',
   'home_team': 17,
   'away_team': 22,
   'home_result': 2,
   'away_result': 0,
   'home_penalty': None,
   'away_penalty': None,
   'winner': 17,
   'date': '2018-07-02T18:00:00+04:00',
   'stadium': 7,
   'channels': [3, 6, 14, 15],
   'finished': True,
   'matchday': 4},
  {'name': 54,
   'type': 'qualified',
   'home_team': 25,
   'away_team': 32,
   'home_result': 3,
   'away_result': 2,
   'home_penalty': None,
   'away_penalty': None,
   'winner': 25,
   'date': '2018-07-02T21:00:00+03:00',
   'stadium': 10,
   'channels': [3, 6, 13, 16],
   'finished': True,
   'matchday': 4},
  {'name': 55,
   'type': 'qualified',
   'home_team': 23,
   'away_team': 18,
   'home_result': 1,
   'away_result': 0,
   'home_penalty': None,
   'away_penalty': None,
   'winner': 23,
   'date': '2018-07-03T17:00:00+03:00',
   'stadium': 3,
   'channels': [4, 6, 14, 16],
   'finished': True,
   'matchday': 4},
  {'name': 56,
   'type': 'qualified',
   'home_team': 31,
   'away_team': 28,
   'home_result': 1,
   'away_result': 1,
   'home_penalty': 3,
   'away_penalty': 4,
   'winner': 28,
   'date': '2018-07-03T21:00:00+03:00',
   'stadium': 2,
   'channels': [3, 6, 13, 15],
   'finished': True,
   'matchday': 4}]}

In [175]:
#On converti chaque dictionnaires imbriqués en Df et on ajoute une colonne de reference(round) pour savoir de quel Df il vient)
round_16 = data["knockout"]["round_16"]["matches"]
df_round_16 = pd.DataFrame(round_16)
df_round_16["round"] = "Huitième de finale"
df_round_16.head(5)

,name,type,home_team,away_team,home_result,away_result,home_penalty,away_penalty,winner,date,stadium,channels,finished,matchday,round
0,49,qualified,4,5,2,1,NaN,NaN,4,2018-06-30T21:00:00+03:00,11,"[4, 13, 15]",True,4,Huitième de finale
1,50,qualified,9,13,4,3,NaN,NaN,9,2018-06-30T17:00:00+03:00,5,"[4, 6, 13, 15]",True,4,Huitième de finale
2,51,qualified,6,1,1,1,3.0,4.0,1,2018-07-01T17:00:00+03:00,1,"[3, 13, 15]",True,4,Huitième de finale
3,52,qualified,15,12,1,1,3.0,2.0,15,2018-07-01T21:00:00+03:00,6,"[4, 6, 13, 15]",True,4,Huitième de finale
4,53,qualified,17,22,2,0,NaN,NaN,17,2018-07-02T18:00:00+04:00,7,"[3, 6, 14, 15]",True,4,Huitième de finale

In [176]:
#De meme pour les 4 autres 
df_round_8 = pd.DataFrame(data["knockout"]["round_8"]["matches"])
df_round_8["round"] = "Quarts de finale"
df_round_4 = pd.DataFrame(data["knockout"]["round_4"]["matches"])
df_round_4["round"] = "Demi-finales"
df_round_2_loser = pd.DataFrame(data["knockout"]["round_2_loser"]["matches"])
df_round_2_loser["round"] = "Troisième place"
df_round_2 = pd.DataFrame(data["knockout"]["round_2"]["matches"])
df_round_2["round"] = "Finale"

In [177]:
#On concatène les 5 df ensemble pour avoir l'ensemble des compétitions 
df_round = pd.concat([df_round_16,df_round_8, df_round_4,df_round_2_loser,df_round_2])

In [178]:
#On reset les index pour ne pas avoir de doublons
df_round.reset_index(drop=True,inplace=True)
df_round.head(5)

,name,type,home_team,away_team,home_result,away_result,home_penalty,away_penalty,winner,date,stadium,channels,finished,matchday,round
0,49,qualified,4,5,2,1,NaN,NaN,4,2018-06-30T21:00:00+03:00,11,"[4, 13, 15]",True,4,Huitième de finale
1,50,qualified,9,13,4,3,NaN,NaN,9,2018-06-30T17:00:00+03:00,5,"[4, 6, 13, 15]",True,4,Huitième de finale
2,51,qualified,6,1,1,1,3.0,4.0,1,2018-07-01T17:00:00+03:00,1,"[3, 13, 15]",True,4,Huitième de finale
3,52,qualified,15,12,1,1,3.0,2.0,15,2018-07-01T21:00:00+03:00,6,"[4, 6, 13, 15]",True,4,Huitième de finale
4,53,qualified,17,22,2,0,NaN,NaN,17,2018-07-02T18:00:00+04:00,7,"[3, 6, 14, 15]",True,4,Huitième de finale

In [179]:
#Suppression des colonnes qui ne nous sont pas utiles
df_round = df_round.drop(columns=["name", "home_penalty", "away_penalty", "winner", "channels", "finished", "matchday", "type"])

In [180]:
df_round.head(3)

,home_team,away_team,home_result,away_result,date,stadium,round
0,4,5,2,1,2018-06-30T21:00:00+03:00,11,Huitième de finale
1,9,13,4,3,2018-06-30T17:00:00+03:00,5,Huitième de finale
2,6,1,1,1,2018-07-01T17:00:00+03:00,1,Huitième de finale

In [181]:
df_groups.head(3)

,name,type,home_team,away_team,home_result,away_result,date,stadium,channels,finished,matchday,groups
0,1,group,1,2,5,0,2018-06-14T18:00:00+03:00,1,"[4, 6, 13, 17, 20, 22]",True,1,a
1,2,group,3,4,0,1,2018-06-15T17:00:00+05:00,12,"[3, 6, 14, 17, 20, 22]",True,1,a
2,17,group,1,3,3,1,2018-06-19T21:00:00+03:00,3,"[3, 6, 13, 17, 15, 21, 22]",True,2,a

In [182]:
#On réarrange le df groups (poules) pour pouvoir le concatecter avec le df round 
df_groups = df_groups.drop(columns=["name", "channels", "finished", "matchday", "groups"])
df_groups = df_groups.rename(columns={"type":"round" })
df_groups["round"] = df_groups["round"].replace(to_replace={"group" : "Poules"})
df_groups.head(1)

,round,home_team,away_team,home_result,away_result,date,stadium
0,Poules,1,2,5,0,2018-06-14T18:00:00+03:00,1

In [183]:
#on concatène le df round et le df groups
df = pd.concat([df_round,df_groups])

In [184]:
#converti la date pour n'avoir que l'année, le mois et le jour
df["date"] = pd.to_datetime(df["date"], utc=True).dt.date

In [185]:
# Donc on merge avec le df Teams pour recuperer les noms des team 
df = df.merge(df_teams, how="left", left_on="home_team", right_on ="id" )
df = df.merge(df_teams, how="left", left_on="away_team", right_on ="id" )
df.head(2)

,home_team,away_team,home_result,away_result,date,stadium,round,id_x,name_x,id_y,name_y
0,4,5,2,1,2018-06-30,11,Huitième de finale,4,Uruguay,5,Portugal
1,9,13,4,3,2018-06-30,5,Huitième de finale,9,France,13,Argentina

In [186]:
df = df.drop(columns=["home_team", "away_team", "id_x", "id_y"])

In [187]:
df = df.rename(columns={"name_x": "home_team", "name_y" : "away_team", })

In [188]:
# City => utilise le df_stadium pour prendre l'id lié au stade
df = df.merge(df_stadiums, how="left", left_on="stadium", right_on ="id" )
df.head(2)

,home_result,away_result,date,stadium,round,home_team,away_team,id,city
0,2,1,2018-06-30,11,Huitième de finale,Uruguay,Portugal,11,Sochi
1,4,3,2018-06-30,5,Huitième de finale,France,Argentina,5,Kazan

In [189]:
df = df.drop(columns=["stadium","id"])

In [190]:
# colonne resultats : 
def function(row): 
    if row["home_result"]> row["away_result"]:
        return "home_team"
    elif  row["home_result"]< row["away_result"] :
        return "away_home"
    else : 
        return "draw"

df["result"] = df.apply(function, axis=1)

In [191]:
# edition : 
df["edition"] = pd.to_datetime(df["date"]).dt.year

In [192]:
df

,home_result,away_result,date,round,home_team,away_team,city,result,edition
0,2,1,2018-06-30,Huitième de finale,Uruguay,Portugal,Sochi,home_team,2018
1,4,3,2018-06-30,Huitième de finale,France,Argentina,Kazan,home_team,2018
2,1,1,2018-07-01,Huitième de finale,Spain,Russia,Moscow,draw,2018
3,1,1,2018-07-01,Huitième de finale,Croatia,Denmark,Nizhny Novgorod,draw,2018
4,2,0,2018-07-02,Huitième de finale,Brazil,Mexico,Samara,home_team,2018
...,...,...,...,...,...,...,...,...,...
59,1,2,2018-06-19,Poules,Colombia,Japan,Saransk,away_home,2018
60,0,3,2018-06-24,Poules,Poland,Colombia,Kazan,away_home,2018
61,2,2,2018-06-24,Poules,Japan,Senegal,Yekaterinburg,draw,2018
62,0,1,2018-06-28,Poules,Japan,Poland,Volgograd,away_home,2018
63,0,1,2018-06-28,Poules,Senegal,Colombia,Samara,away_home,2018